# Решение задач по numpy.
Задачник лежит здесь:
https://docs.google.com/spreadsheets/d/1v1_X6zRlwRVjULZSrRvBYAG_raUPjTI0Ceruwh6vNXw/edit#gid=2019320840


In [1]:
import numpy as np
import time

## Array attributes

Задача 1.

Создайте массив длины 10, заполненный нулями
Сделайте полученный массив неизменяемым

In [ ]:
a = np.zeros(10)
a.setflags(write=False)
a

In [ ]:
try:
    a[1] = 2
    print('Think about it...')
except:
    print('Done')

Задача 2.

Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
Составьте из полученных массивов координатную сеть (meshgrid)

In [ ]:
a = np.linspace(start=0,stop=2*np.pi, num=5)
a

In [ ]:
b = np.logspace(base=10, start=1, stop=2,num=5)
b

In [ ]:
c = np.meshgrid(a,b)
c

Задача 3. Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [ ]:
a = np.zeros(shape=(5,5))
for i in range(4):
  a[i+1,i] = i + 1
a

In [ ]:
a = np.eye(5, k=-1)
a = a * range(1,6,1)
a

In [ ]:
a = np.diag(range(1,5,1), k=-1)
a

Задача 4.

Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
Создайте массив из построенного генератора

In [14]:
def gen(lenght):
    c = 0
    yield c
    while c < lenght-1:
        c += 1
        yield c

arr_lenght = 10
arr = np.zeros(arr_lenght)
for i in gen(arr_lenght):
    arr[i] = i
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Array arithmetic operations

Задача 5. 
Что будет выведено на экран? a = np.arange(4).reshape(2,2) a += 0.5 print(a)

In [ ]:
a = np.arange(4.).reshape(2,2) #dtype=float
a += .5
a

формулировка задачи приводит в выводу ошибки, т.к. создается массив int. чтобы данная конструкция работала надо явно указать тип переменной. Либо через dtype=float, либо задав значение как 4 с точкой на конце.

Задача 6. 
Что будет выведено на экран? a = np.array([1]) if a: print(""True"") else: print(""False"")
a = np.array([1, 2, 3]) if a: print(""True"") else: print(""False"")

In [ ]:
a = np.array([0])
if a:
  print('True')
else:
  print('False')

Вернет True при любом значении массива, кроме 0. Или инициализации пустого массива.

In [ ]:
a = np.array([0,0,1])
if a.all(): #should use any() or all()
  print('True')
else:
  print('False')

Вернет ошибку. Чтобы массив длинной >1 обрабатывался корректно нужно использовать all() или any()

## Floating Point Special Values

Что будет выведено на экран?
print(0 * np.nan)
print(np.nan - np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(-np.inf < np.nan < np.inf)

In [ ]:
print(0 * np.nan)

In [ ]:
print(np.nan - np.nan)

In [ ]:
print(np.nan == np.nan)

сравнение np.nan == np.nan возвращает False. Что корректно сравнивать np.nan надо использовать специальную функцию.

In [17]:
import pandas as pd
pd.isna(np.nan)

True

In [15]:
print(np.nan is np.nan)

True


In [ ]:
print(-np.inf < np.nan < np.inf)

Что будет выведено на экран?
print(np.isnan(np.array([np.nan]).astype(np.int)))

In [ ]:
print(np.isnan(np.array([np.nan]).astype(np.int)))

Интересно, что в данной контрукции пандас возвращает False

In [18]:
print(pd.isna(np.array([np.nan]).astype(np.int)))

[False]


## Broadcasting rules

Задача 9.
1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [ ]:
a = np.array([0,10,20,30])
b = np.zeros(shape=(4,5))
b[:,0] = a.reshape(1,-1)
for i in range(1,5):
    b[:,i] = b[:,i-1] + 1
b

In [ ]:
a = np.arange(0,31,10).reshape(-1,1)
b= np.array([0,1,2,3,4])
a+b

Задача 10.
Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

In [ ]:
a = np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)
a.shape

## Basic Slicing and Indexing

Задача 11.
Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [ ]:
# %%timeit
a = np.zeros([8,8],dtype=int)
for i in range(8):
    for j in range(8):
        if ((i+j) % 2) == 0:
            a[i,j] = 1
a

In [ ]:
# %%timeit
a=[0,1] * 4
b = [1, 0] * 4
c = np.array([b, a]*4).reshape(-1,8)
c

In [20]:
n = 8
a = np.zeros([n,n], dtype=int)
a[[range(0,n,2)], ::2] = 1
a[[range(1,n,2)], 1::2] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задача 12.
1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [ ]:
a = np.arange(1,6,1)
b = np.zeros(a.shape[0]*2-1)

b[::2] = a
print(b)

Задача 13.
Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])

In [ ]:
x = np.arange(36).reshape(3,4,3)
print(x[...,0,...])

In [ ]:
x = np.arange(36).reshape(2,3,2,3) print(x[...,0,...])

Будет выведена ошибка, объект Ellipsys можно использовать только один раз. Трактуется как "добавить столько ':' сколько нужно.

В чем разница между x[:,0] и x[...,0] ?

Двоеточие подразумевает одну размерность, троеточие любое количество.

Задача 14.
Что будет выведено на экран (!!!!)

In [6]:
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]]


Важная особенность nupmy в том, что при использовании листа или массива возвращается копия среза массива.
Использование только среза или числа возвращает ссылки на первоначальный массив. Через такие массивы возможны операции с первоначальным массивом.

## Boolean array indexing

Задача 15. Замените отрицательные элементы массива нулем.

In [ ]:
a = np.arange(-5, 5, 1)
a[a<0] = 0
a

Задача 16.
На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [48]:
%%timeit
def foo(x):
    mask = np.ones(x.shape,dtype=bool)
    for i in range(x.shape[0]):
        rows = x[i,:]
        if len(np.unique(rows)) == 1:
            mask[i,:] = False
        else:
            mask[i,:] = True
    return mask


x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = foo(x)
x = x[mask].reshape(-1,x.shape[1])
x

33.1 µs ± 538 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [47]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = np.zeros(x.shape, dtype=bool)
m = np.array([np.sum(x,axis=1)/x[:,0] != x.shape[1]],)
mask.T[:] = m
x = x[mask].reshape(-1, x.shape[1])

15.3 µs ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
m = (x[:,0] != x[:,1]) | (x[:,1] != x[:,2])
mask = np.zeros(x.shape, dtype=bool)
mask.T[:] = m
# x = x[mask].reshape(-1, x.shape[1])
# print(x[mask])

8.83 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = (x[:,[0]] != x[:,1:]).any(axis=1)
x = x[mask]
x

11.5 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Задача 17.
Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [ ]:
%%timeit

def foo(arr):
    mask = np.zeros(arr.shape,dtype=bool)
    for i in range(len(arr)):
        if i == 0:
            if arr[i] <= arr[i+1]:
                mask[i] = True
        elif i == (len(arr) - 1):
            if arr[i] <= arr[i-1]:
                mask[i] = True
        else:
            if arr[i-1] >= arr[i] <= arr[i+1]:
                mask[i] = True
    return mask

a = np.random.randint(0,5,10)
# print(a)
mask = foo(a)
# print(mask)
a = a[mask]
a


In [68]:
%%timeit
a = np.random.randint(0,5,10)
# print(a)
mask1 = [a[1:]<=a[:-1]]
mask2 = [a[:-1]<=a[1:]]
mask1 = np.append(True, mask1)
mask2 = np.append(mask2, True)
mask = mask1 * mask2
a = a[mask]
a

26 µs ± 332 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [79]:
%%timeit
a = np.random.randint(0,5,10)
# print(a)
mask = np.ones(10,dtype=bool)
mask[1:] *= (a[1:] <= a[:-1])
mask[:-1] *= (a[:-1] <= a[1:])
a = a[mask]
a

17.3 µs ± 853 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Integer array indexing

Задача 18.
1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a[:,1] = np.sort(a[:,1])
a

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a, a[:,1], sep='\n', end='\n')
index = np.argsort(a[:,1], axis=0)
print(index)
a = a[[index], :]
a

Задача 19.
Поменяйте местами первую и вторую строки двумерного массива.

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a = a[[1,0,2], :]
a

Задача 20
1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [ ]:
a = np.arange(0,15,1).reshape(3,5)
print(a)
print(a[[0,2],:][:,[1,3]])
print(a)

Задача 21
Что будет выведено на экран?


In [ ]:
x = np.arange(5)
print(x[[0,0,1]])
# x[[0,0,1]] = range(3)
# print(x)
# x[[1,2,1]] += 1 # x[[1,2,1]] = x[[1,2,1]] + 1
print(x)

In [ ]:
x[[1,2,1]] + 1

## Functions and Methods Overview

Задача 22.
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [ ]:
a = np.arange(0,1600,1).reshape(40, 40)

In [ ]:
%%timeit
a.flatten()

In [ ]:
%%timeit
a.ravel()

In [ ]:
%%timeit
a.reshape(-1,)

In [ ]:
import timeit
a = np.arange(0,1500,1).reshape(30,50)
timeit.timeit(lambda: a.resize((a.shape[0]*a.shape[1],)),number=1)
# print(a)

Задача 23.
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним


In [ ]:
a = np.random.randint(0,5,10)
a = a.astype(np.float32)
print(a)
max_ind = np.argwhere(a == np.max(a))
print(np.mean(a))
a[max_ind] = np.mean(a)
a

Задача 24.
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [80]:
a = np.random.randint(2,6,size=(6,6))
print(a)
sum = np.sum(a, axis=1)
print(sum)
min_col = np.min(a, axis=0)
print(min_col)
answer = sum / min_col
answer

[[2 5 5 5 5 5]
 [4 5 2 3 5 4]
 [5 2 2 5 5 2]
 [2 2 3 2 5 3]
 [3 3 4 4 3 5]
 [4 4 4 3 5 5]]
[27 23 21 17 22 25]
[2 2 2 2 3 2]


array([13.5       , 11.5       , 10.5       ,  8.5       ,  7.33333333,
       12.5       ])

Задача 25.
1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [81]:
a = np.random.uniform(1,8,10)
a = (a - a.min()) / (a.max()-a.min())
a

array([0.        , 0.73319714, 0.71607321, 0.21066266, 0.78464417,
       0.71659463, 0.43438248, 0.56620262, 0.52478215, 1.        ])

Задача 26.
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [88]:
a = np.random.uniform(size=(6,4))
a[::2, 0::1] = np.nan
print(a)
mean = np.nanmean(a, axis=0)
# print(mean)
cell = np.argwhere([np.isnan(a) == True])
# print(cell[:])
nan_value = mean[cell[:,2]]
# print(nan_value)
a[np.isnan(a) == True] = nan_value
a
# a[mask_nan].reshape(-1,a.shape[1]) = mean
# a

[[       nan        nan        nan        nan]
 [0.91439397 0.19076393 0.43063015 0.86955866]
 [       nan        nan        nan        nan]
 [0.77808264 0.01462579 0.15081033 0.34785065]
 [       nan        nan        nan        nan]
 [0.20291167 0.2004062  0.66808397 0.77515709]]


array([[0.63179609, 0.13526531, 0.41650815, 0.6641888 ],
       [0.91439397, 0.19076393, 0.43063015, 0.86955866],
       [0.63179609, 0.13526531, 0.41650815, 0.6641888 ],
       [0.77808264, 0.01462579, 0.15081033, 0.34785065],
       [0.63179609, 0.13526531, 0.41650815, 0.6641888 ],
       [0.20291167, 0.2004062 , 0.66808397, 0.77515709]])

Задача 27.
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [96]:
a = np.random.randint(0,2,size=(3,6))
print(a)
mask = (a==0)
# print(mask)
pos = mask.all(axis=0).any()
pos

[[0 1 1 0 0 1]
 [1 1 1 0 0 0]
 [1 0 0 0 1 0]]


True

In [94]:
#apply_along_axis 

Задача 28.
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [100]:
a = np.random.randint(0,10,size=(3,4,3,4))
# print(np.sum(a, axis=(-2,-1))) # одна трактовка
print(np.sum(a, axis=-2)) #другая трактовка (сумма по одной и по другой оси)
print(np.sum(a, axis=-1))

[[[19 14 18  4]
  [10 14 19  8]
  [11  6 12 16]
  [ 7 13 12 11]]

 [[17 17 10 21]
  [ 2  3 17 12]
  [15 19 16 10]
  [14 15 16 16]]

 [[ 9 11 14 13]
  [10  6 17 22]
  [10  7 24 15]
  [17 20 11 17]]]
[[[12 25 18]
  [10 19 22]
  [19 18  8]
  [16 15 12]]

 [[23 17 25]
  [20 11  3]
  [18 20 22]
  [26 16 19]]

 [[19 14 14]
  [25 16 14]
  [15 24 17]
  [22 10 33]]]


Задача 29.
1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [153]:
%%timeit
a = np.random.randint(0,10,100)
b = np.random.uniform(0,2,100)
c = np.zeros(200)
c[::2] = a
c[1::2] = b
c

17.4 µs ± 75.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [154]:
%%timeit
a = np.random.randint(0,10,100)
# print(a)
b = np.random.uniform(0,2,100)
# print(b)
c = np.tile([0,1.],100)
# print(c)
# c = np.stack([a,b], axis=1)
np.place(c, c==0, a)
# print(c)
np.place(c, c==1, b)
# print(c)
c

32.8 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [157]:
%%timeit
a = np.random.randint(0,10,100)
# print(a)
b = np.random.uniform(0,2,100)
# print(b)
c = np.vstack([a,b])
c = c.T.flatten()
c

20.9 µs ± 61.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [156]:
%%timeit
a = np.random.randint(0,10,100)
# print(a)
b = np.random.uniform(0,2,100)
# print(b)
c = np.vstack([a,b])
c = c.T.ravel()
c

20.8 µs ± 94.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Задача 30.
На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) вычислите долю пропущенных значений.

In [105]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
answer = np.isnan(x).sum() / (x.shape[0] * x.shape[1])
answer

0.375

Задача 31.
На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) составьте массив из уникальных значений массива без учета nan

In [112]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
uniq = np.unique(x[~np.isnan(x)])
uniq

array([1., 2., 3., 5.])

Задача 32.
На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [173]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
i, = np.where(x==0)
i = i + 1
maximum = np.choose(i, x, mode='clip').max()
maximum

5

In [166]:
np.append(x[1:],0)

array([2, 0, 3, 0, 0, 5, 7, 0, 0])

Задача 33.
Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [188]:
a = np.random.randint(0,5,10)
b = np.random.randint(0,3,10)
print(a,b)
non_zero, = np.nonzero(b)
c = np.zeros(10)
c[non_zero] = a[non_zero] / b[non_zero]
c

[1 3 4 0 0 2 2 1 0 2] [2 2 1 0 0 0 1 0 1 2]


array([0.5, 1.5, 4. , 0. , 0. , 0. , 2. , 0. , 0. , 1. ])

Задача 34.
Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. 
В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [189]:
x = np.ones(10)
i = np.array([0,1,2,3,5,5,5,8])
x += np.resize(np.bincount(i), x.shape)
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 2.])

Задача 35.
По заданному массиву y = np.bincount([0, 0, 3, 8, 10, 10, 11]) постройте массив x такой, чтобы np.bincount(x) = y

In [151]:
%%timeit
# с точностью до перестановки
def rebincount(arr):
    # arr = arr.astype('uint')
    result = np.array([],dtype=int)
    for i in range(arr.max()):
        result = np.append(result, np.nonzero(arr))
        arr[np.nonzero(arr)] = arr[np.nonzero(arr)] - 1
    return result

y = np.bincount([0, 0, 3, 8, 10, 10, 11])
answer = rebincount(y)
answer

29 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [149]:
%%timeit
def rebincount(arr):
    # arr = arr.astype('uint')
    result = np.array([],dtype=int)
    for i in range(arr.max()):
        indices = np.nonzero(arr)
        result = np.append(result, indices)
        arr[indices] = arr[indices] - 1
    return result

y = np.bincount([0, 0, 3, 8, 10, 10, 11])
answer = rebincount(y)
answer

23.5 µs ± 68.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Интересно, что результат np.nonzero(arr) не хранится в буфере и перевычисляется.

In [155]:
%%timeit
y = np.bincount([0, 0, 3, 8, 10, 10, 11])
x = np.repeat(np.arange(y.size),y)
x

4.02 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Задача 36.
Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива x = np.array([0,1,2,0,6,6,7,4,5,4]).

In [162]:
%%timeit
x = np.array([0,1,2,0,6,6,7,4,5,4])
i = np.bincount(x)
m = np.bincount(i)
answer, = np.where(i == len(m)-1)
answer

4.71 µs ± 176 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [163]:
%%timeit
x = np.array([0,1,2,0,6,6,7,4,5,4])
i = np.bincount(x)
answer, = np.where(i == i.max())
answer

6.83 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Задача 37.
Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]), 
в результате должен получиться список [array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])].

In [68]:
%%timeit
def split_arr(arr):
    m = np.unique(arr[:,0])
    arr_list = []
    for i in m:
        arr_list.append(np.squeeze(arr[np.argwhere(arr[:,0] == i)]))
    return arr_list

x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])

split_arr(x)

49.9 µs ± 58.8 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [69]:
%%timeit
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])
bincount = np.bincount(x[:,0])
indices = np.zeros(len(bincount),dtype=int)
for i in range(len(bincount)):
    indices[i] = bincount[:i].sum()
indices = np.trim_zeros(indices)
arr_split = np.split(x, indices, axis=0)
arr_split

38.1 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [164]:
# %%timeit
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])
bincount = np.bincount(x[:,0])
bincount = bincount[bincount.nonzero()].cumsum()
arr_split = np.split(x, bincount[:-1], axis=0)
arr_split

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

Notes:

indices[indices.nonzero()] работает сильно быстрее чем np.trim_zeros(indices)

Задача 38.
По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, 
содержащих элементы из полуинтервалов [i * 10, (i+1) * 10), i = 0, 1, 2, … ]
Решите задачу на примере массива x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]), 
в результате должен получиться список [array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])].

In [72]:
%%timeit
def split_arr(arr,indices):
    list_arr = []
    for i in range(indices.max()+1):
        list_arr.append(np.sort(arr[np.where(indices == i)]))
    return list_arr

x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])
y = x // 10
split_arr(x,y)

23.9 µs ± 209 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [114]:
%%timeit
x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])
y = x // 10
bincount = np.bincount(y)
indices = bincount.cumsum()
answer = np.split(np.sort(x), indices[:-1])
answer

19 µs ± 1.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Vector Stacking

Задача 39.
Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

In [130]:
arrays = [np.eye(3)*(i+1) for i in range(400)]

In [122]:
arrays

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]]),
 array([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]]),
 array([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])]

In [131]:
%%timeit
np.hstack(arrays)

237 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


преображает массивы в 2d и concatenate их

In [132]:
%%timeit
np.block(arrays)

826 µs ± 27.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [133]:
%%timeit
np.concatenate(arrays,axis=1)

69.2 µs ± 73.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


concatenate возвращает masked array, в котором масками задается отображением массивов, которые мы хотим сцепить.

stack создает новую ось и конкатеринует вдоль неё

In [175]:
np.append(arrays[0], arrays[1],axis=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
np.append работает медленее всех.

Задача 40.

Для двух одномерных массивов x = np.arange(3) и y = np.arange(5) постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [57]:
x = np.arange(3)
y = np.arange(5)
z = np.dstack((np.repeat(x, len(y)), np.tile(y, len(x)))).squeeze()
z

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]])

In [72]:
x = np.arange(3)
y = np.arange(5)
z = np.broadcast(x,y)
z

ValueError: shape mismatch: objects cannot be broadcast to a single shape

Задача 41.

По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индексами.
Решите задачу на примере массивов x = np.array([1,2,3,4]) и y = np.array([5,6,7,8]).

In [60]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = np.dstack((x,y))
z

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

Задача 42.

По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])].

In [85]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]
l = np.asarray(l)
shape = list(l.shape)
shape[0] = shape[0]*2 -1
answer = np.zeros(shape=shape)
answer[::2,:,:] = l
answer

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 9., 10.],
        [11., 12.]]])

## Stride Tricks

Задача 43.

Преобразуйте одномерный массив x = np.array([3,7,2,5,0,9,8,2,4,5]) в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [112]:
from numpy.lib.stride_tricks import as_strided

x = np.array([3,7,2,5,0,9,8,2,4,5]).reshape(1,-1)
shape = [5, x.shape[1]-5]
answer = as_strided(x, shape=shape, strides=(8,8))
answer

(80, 8)


array([[3, 7, 2, 5, 0],
       [7, 2, 5, 0, 9],
       [2, 5, 0, 9, 8],
       [5, 0, 9, 8, 2],
       [0, 9, 8, 2, 4]])

Задача 44.

Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива x = np.arange(49).reshape(7,7).

In [29]:
from numpy.lib.stride_tricks import as_strided

x = np.arange(49).reshape(7,7)
kernel = np.array([3,3])
print(x)
shape = [x.shape[0] // 3, x.shape[1] // 3]
qty_sq = sum(shape)

print(x.strides)
(as_strided(x, 
            shape=(shape[0],shape[1], kernel[0], kernel[1]), 
            strides=(x.strides[0]*kernel[0],x.strides[1]*kernel[1], x.strides[0], x.strides[1]))
 .reshape([shape[0]*shape[1], kernel[0], kernel[1]]))


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
(56, 8)


array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]],

       [[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

## Masked arrays

Задача 45.
Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.

In [35]:
x = np.zeros(100)
x[0] = 100
mean = np.mean(x)
std = np.std(x)
var = np.var(x)
print(mean, std, var)


1.0 9.9498743710662 99.0
