# Решение задач по numpy.
Задачник лежит здесь:
https://docs.google.com/spreadsheets/d/1v1_X6zRlwRVjULZSrRvBYAG_raUPjTI0Ceruwh6vNXw/edit#gid=2019320840


In [1]:
import numpy as np
import time

## Array attributes

Задача 1.

Создайте массив длины 10, заполненный нулями
Сделайте полученный массив неизменяемым

In [ ]:
a = np.zeros(10)
a.setflags(write=False)
a

In [ ]:
try:
    a[1] = 2
    print('Think about it...')
except:
    print('Done')

Задача 2.

Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
Составьте из полученных массивов координатную сеть (meshgrid)

In [ ]:
a = np.linspace(start=0,stop=2*np.pi, num=5)
a

In [ ]:
b = np.logspace(base=10, start=1, stop=2,num=5)
b

In [ ]:
c = np.meshgrid(a,b)
c

Задача 3. Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [ ]:
a = np.zeros(shape=(5,5))
for i in range(4):
  a[i+1,i] = i + 1
a

In [ ]:
a = np.eye(5, k=-1)
a = a * range(1,6,1)
a

In [ ]:
a = np.diag(range(1,5,1), k=-1)
a

Задача 4.

Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
Создайте массив из построенного генератора

In [14]:
def gen(lenght):
    c = 0
    yield c
    while c < lenght-1:
        c += 1
        yield c

arr_lenght = 10
arr = np.zeros(arr_lenght)
for i in gen(arr_lenght):
    arr[i] = i
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Array arithmetic operations

Задача 5. 
Что будет выведено на экран? a = np.arange(4).reshape(2,2) a += 0.5 print(a)

In [ ]:
a = np.arange(4.).reshape(2,2) #dtype=float
a += .5
a

формулировка задачи приводит в выводу ошибки, т.к. создается массив int. чтобы данная конструкция работала надо явно указать тип переменной. Либо через dtype=float, либо задав значение как 4 с точкой на конце.

Задача 6. 
Что будет выведено на экран? a = np.array([1]) if a: print(""True"") else: print(""False"")
a = np.array([1, 2, 3]) if a: print(""True"") else: print(""False"")

In [ ]:
a = np.array([0])
if a:
  print('True')
else:
  print('False')

Вернет True при любом значении массива, кроме 0. Или инициализации пустого массива.

In [ ]:
a = np.array([0,0,1])
if a.all(): #should use any() or all()
  print('True')
else:
  print('False')

Вернет ошибку. Чтобы массив длинной >1 обрабатывался корректно нужно использовать all() или any()

## Floating Point Special Values

Что будет выведено на экран?
print(0 * np.nan)
print(np.nan - np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(-np.inf < np.nan < np.inf)

In [ ]:
print(0 * np.nan)

In [ ]:
print(np.nan - np.nan)

In [ ]:
print(np.nan == np.nan)

сравнение np.nan == np.nan возвращает False. Что корректно сравнивать np.nan надо использовать специальную функцию.

In [17]:
import pandas as pd
pd.isna(np.nan)

True

In [15]:
print(np.nan is np.nan)

True


In [ ]:
print(-np.inf < np.nan < np.inf)

Что будет выведено на экран?
print(np.isnan(np.array([np.nan]).astype(np.int)))

In [ ]:
print(np.isnan(np.array([np.nan]).astype(np.int)))

Интересно, что в данной контрукции пандас возвращает False

In [18]:
print(pd.isna(np.array([np.nan]).astype(np.int)))

[False]


## Broadcasting rules

Задача 9.
1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [ ]:
a = np.array([0,10,20,30])
b = np.zeros(shape=(4,5))
b[:,0] = a.reshape(1,-1)
for i in range(1,5):
    b[:,i] = b[:,i-1] + 1
b

In [ ]:
a = np.arange(0,31,10).reshape(-1,1)
b= np.array([0,1,2,3,4])
a+b

Задача 10.
Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

In [ ]:
a = np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)
a.shape

## Basic Slicing and Indexing

Задача 11.
Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [ ]:
# %%timeit
a = np.zeros([8,8],dtype=int)
for i in range(8):
    for j in range(8):
        if ((i+j) % 2) == 0:
            a[i,j] = 1
a

In [ ]:
# %%timeit
a=[0,1] * 4
b = [1, 0] * 4
c = np.array([b, a]*4).reshape(-1,8)
c

In [20]:
n = 8
a = np.zeros([n,n], dtype=int)
a[[range(0,n,2)], ::2] = 1
a[[range(1,n,2)], 1::2] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задача 12.
1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [ ]:
a = np.arange(1,6,1)
b = np.zeros(a.shape[0]*2-1)

b[::2] = a
print(b)

Задача 13.
Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])

In [ ]:
x = np.arange(36).reshape(3,4,3)
print(x[...,0,...])

In [ ]:
x = np.arange(36).reshape(2,3,2,3) print(x[...,0,...])

Будет выведена ошибка, объект Ellipsys можно использовать только один раз. Трактуется как "добавить столько ':' сколько нужно.

В чем разница между x[:,0] и x[...,0] ?

Двоеточие подразумевает одну размерность, троеточие любое количество.

Задача 14.
Что будет выведено на экран (!!!!)

In [6]:
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]]


Важная особенность nupmy в том, что при использовании листа или массива возвращается копия среза массива.
Использование только среза или числа возвращает ссылки на первоначальный массив. Через такие массивы возможны операции с первоначальным массивом.

## Boolean array indexing

Задача 15. Замените отрицательные элементы массива нулем.

In [ ]:
a = np.arange(-5, 5, 1)
a[a<0] = 0
a

Задача 16.
На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [48]:
%%timeit
def foo(x):
    mask = np.ones(x.shape,dtype=bool)
    for i in range(x.shape[0]):
        rows = x[i,:]
        if len(np.unique(rows)) == 1:
            mask[i,:] = False
        else:
            mask[i,:] = True
    return mask


x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = foo(x)
x = x[mask].reshape(-1,x.shape[1])
x

33.1 µs ± 538 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [47]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = np.zeros(x.shape, dtype=bool)
m = np.array([np.sum(x,axis=1)/x[:,0] != x.shape[1]],)
mask.T[:] = m
x = x[mask].reshape(-1, x.shape[1])

15.3 µs ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
m = (x[:,0] != x[:,1]) | (x[:,1] != x[:,2])
mask = np.zeros(x.shape, dtype=bool)
mask.T[:] = m
# x = x[mask].reshape(-1, x.shape[1])
# print(x[mask])

8.83 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = (x[:,[0]] != x[:,1:]).any(axis=1)
x = x[mask]
x

11.5 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Задача 17.
Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [ ]:
%%timeit

def foo(arr):
    mask = np.zeros(arr.shape,dtype=bool)
    for i in range(len(arr)):
        if i == 0:
            if arr[i] <= arr[i+1]:
                mask[i] = True
        elif i == (len(arr) - 1):
            if arr[i] <= arr[i-1]:
                mask[i] = True
        else:
            if arr[i-1] >= arr[i] <= arr[i+1]:
                mask[i] = True
    return mask

a = np.random.randint(0,5,10)
# print(a)
mask = foo(a)
# print(mask)
a = a[mask]
a


In [ ]:
%%timeit
a = np.random.randint(0,5,10)
mask1 = [a[1:]<=a[:-1]]
mask2 = [a[:-1]<=a[1:]]
mask1 = np.append(8, mask1)
mask2 = np.append(mask2, True)
mask = mask1 * mask2
a = a[mask]
a

## Integer array indexing

Задача 18.
1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a[:,1] = np.sort(a[:,1])
a

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a, a[:,1], sep='\n', end='\n')
index = np.argsort(a[:,1], axis=0)
print(index)
a = a[[index], :]
a

Задача 19.
Поменяйте местами первую и вторую строки двумерного массива.

In [ ]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a = a[[1,0,2], :]
a

Задача 20
1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [ ]:
a = np.arange(0,15,1).reshape(3,5)
print(a)
print(a[[0,2],:][:,[1,3]])
print(a)


Задача 21
Что будет выведено на экран?


In [ ]:
x = np.arange(5)
print(x[[0,0,1]])
# x[[0,0,1]] = range(3)
# print(x)
# x[[1,2,1]] += 1 # x[[1,2,1]] = x[[1,2,1]] + 1
print(x)

In [ ]:
x[[1,2,1]] + 1

## Functions and Methods Overview

Задача 22.
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [ ]:
a = np.arange(0,1600,1).reshape(40, 40)

In [ ]:
%%timeit
a.flatten()

In [ ]:
%%timeit
a.ravel()

In [ ]:
%%timeit
a.reshape(-1,)

In [ ]:
import timeit
a = np.arange(0,1500,1).reshape(30,50)
timeit.timeit(lambda: a.resize((a.shape[0]*a.shape[1],)),number=1)
# print(a)

In [ ]:
a

In [ ]:
a.shape

In [ ]:
# %%timeit
a.shape = (-1,)
# print(a)

In [ ]:
a = a.T

In [ ]:
a

In [ ]:
a[100]

Задача 23.
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним


In [ ]:
a = np.random.randint(0,5,10)
a = a.astype(np.float32)
print(a)
max_ind = np.argwhere(a == np.max(a))
print(np.mean(a))
a[max_ind] = np.mean(a)
a

Задача 24.
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [ ]:
a = np.random.randint(2,6,size=(6,6))
print(a)
sum = np.sum(a, axis=1)
print(sum)
min_col = np.min(a, axis=0)
print(min_col)
answer = sum / min_col
answer

Задача 25.
1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [ ]:
a = np.random.uniform(1,8,10)
a = (a - a.min()) / (a.max()-a.min())
a

Задача 26.
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [ ]:
a = np.random.uniform(size=(6,4))
a[::2, 0::1] = np.nan
print(a)
mean = np.nanmean(a, axis=0)
print(mean)
cell = np.argwhere([np.isnan(a) == True])
# print(cell[:,2])
nan_value = mean[cell[:,2]]
# print(nan_value)
a[np.isnan(a) == True] = nan_value
a
# a[mask_nan].reshape(-1,a.shape[1]) = mean
# a

Задача 27.
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [ ]:
a = np.random.randint(0,2,size=(3,6))
print(a)
mask = a==0
# print(mask)
pos = mask.all(axis=0).any()
pos

In [ ]:
#apply_along_axis 

Задача 28.
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [ ]:
a = np.random.randint(0,10,size=(3,4,3,4))
# print(np.sum(a, axis=(2,3)))
print(np.sum(a, axis=2))
print(np.sum(a, axis=3))

Задача 29.
1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [ ]:
%%timeit
a = np.random.randint(0,10,10)
b = np.random.uniform(0,2,10)
c = np.zeros(20)
c[::2] = a
c[1::2] = b
c

In [ ]:
# %%timeit
a = np.random.randint(0,10,10)
b = np.random.uniform(0,2,10)
c = np.add(a,b)
c

Задача 32.
На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [ ]:
#np.searchsorted(x, 0, side='right')

Задача 34.
Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. 
В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [ ]:
x = np.ones(10)
i = np.array([0,1,2,3,5,5,5,8])
x += np.resize(np.bincount(i), x.shape)
x