In [3]:
import numpy as np
import time

Задача 1.

Создайте массив длины 10, заполненный нулями
Сделайте полученный массив неизменяемым

In [2]:
a = np.zeros(10)
a.setflags(write=False)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
try:
  a[1] = 2
except:
    print('Done')

Задача 2.

Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
Составьте из полученных массивов координатную сеть (meshgrid)

In [ ]:
a = np.linspace(start=0,stop=2*np.pi, num=5)
a

In [ ]:
b = np.logspace(base=10, start=1, stop=2,num=5)
b

In [ ]:
c = np.meshgrid(a,b)
c

Задача 3. Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [ ]:
a = np.zeros(shape=(5,5))
for i in range(4):
  a[i+1,i] = i + 1
a

Задача 4.

Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
Создайте массив из построенного генератора

In [ ]:
c = 0
def gen():
    global c
    c += 1
    return c

arr_lenght = 10
arr = np.zeros(arr_lenght)
for i in range(arr_lenght):
  arr[i] = gen() - 1
arr

Задача 5. 
Что будет выведено на экран? a = np.arange(4).reshape(2,2) a += 0.5 print(a)

In [3]:
a = np.arange(4.).reshape(2,2) #dtype=float
a += .5
a

array([[0.5, 1.5],
       [2.5, 3.5]])

формулировка задачи приводит в выводу ошибки, т.к. создается массив int. чтобы данная конструкция работала надо явно указать тип переменной. Либо через dtype=float, либо задав значение как 4.

Задача 6. 
Что будет выведено на экран? a = np.array([1]) if a: print(""True"") else: print(""False"")
a = np.array([1, 2, 3]) if a: print(""True"") else: print(""False"")

In [ ]:
a = np.array([0])
if a:
  print('True')
else:
  print('False')

Вернет True при любом значении массива, кроме 0. Или инициализации пустого массива.

In [ ]:
a = np.array([0,0,1])
if a.all(): #should use any() or all()
  print('True')
else:
  print('False')

Вернет ошибку. Чтобы массив длинной >1 обрабатывался корректно нужно использовать all() или any()

Что будет выведено на экран?
print(0 * np.nan)
print(np.nan - np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(-np.inf < np.nan < np.inf)

In [4]:
print(0 * np.nan)

nan


In [5]:
print(np.nan - np.nan)

nan


In [6]:
print(np.nan == np.nan)

False


чтобы np.nan == np.nan возвращал True надо расчехлять пандас:

In [20]:
import pandas as pd
pd.isna(np.nan)

True

In [7]:
print(np.nan is np.nan)

True


In [8]:
print(-np.inf < np.nan < np.inf)

False


Что будет выведено на экран?
print(np.isnan(np.array([np.nan]).astype(np.int)))

In [24]:
print(np.isnan(np.array([np.nan]).astype(np.int)))

[False]


Интересно, что в данной контрукции пандас возвращает False

In [28]:
print(pd.isna(np.array([np.nan]).astype(np.int)))

[False]


Задача 9.
1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [41]:
a = np.array([0,10,20,30])
b = np.zeros(shape=(4,5))
b[:,0] = a.reshape(1,-1)
for i in range(1,5):
    b[:,i] = b[:,i-1] + 1
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.],
       [30., 31., 32., 33., 34.]])

In [47]:
a = np.arange(0,31,10).reshape(-1,1)
b= np.array([0,1,2,3,4])
a+b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

Задача 10.
Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

In [42]:
a = np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)
a

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

Задача 11.
Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [30]:
# %%timeit
a = np.zeros([8,8],dtype=int)
for i in range(8):
    for j in range(8):
        if ((i+j) % 2) == 0:
            a[i,j] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [32]:
# %%timeit
a=[0,1] * 4
b = [1, 0] * 4
c = np.array([b, a]*4).reshape(-1,8)
c

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задача 12.
1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [27]:
a = np.arange(1,6,1)
b = np.zeros(a.shape[0]*2-1)

b[::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]


Задача 13.
Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])

In [39]:
x = np.arange(36).reshape(4,9)
print(x)
print(x[0, ...])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
[0 1 2 3 4 5 6 7 8]


В чем разница между x[:,0] и x[...,0] ?

Задача 14.
Что будет выведено на экран (!!!!)

In [87]:
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]]


Задача 15. Замените отрицательные элементы массива нулем.

In [50]:
a = np.arange(-5, 5, 1)
a[a<0] = 0
a

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

Задача 16.
На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [107]:
%%timeit
def foo(x):
    mask = np.ones(x.shape,dtype=bool)
    for i in range(x.shape[0]):
        rows = x[i,:]
        if len(np.unique(rows)) == 1:
            mask[i,:] = False
        else:
            mask[i,:] = True
    return mask


x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = foo(x)
x = x[mask].reshape(-1,x.shape[1])
x

32.8 µs ± 141 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [174]:
%%timeit
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
mask = np.zeros(x.shape, dtype=bool)
m = np.array([np.sum(x,axis=1)/x[:,0] != x.shape[1]],)
mask.T[:] = m
x = x[mask].reshape(-1, x.shape[1])
x

15.5 µs ± 402 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Задача 17.
Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [104]:
%%timeit

def foo(arr):
    mask = np.zeros(arr.shape,dtype=bool)
    for i in range(len(arr)):
        if i == 0:
            if arr[i] <= arr[i+1]:
                mask[i] = True
        elif i == (len(arr) - 1):
            if arr[i] <= arr[i-1]:
                mask[i] = True
        else:
            if arr[i-1] >= arr[i] <= arr[i+1]:
                mask[i] = True
    return mask

a = np.random.randint(0,5,10)
# print(a)
mask = foo(a)
# print(mask)
a = a[mask]
a


13.8 µs ± 118 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [105]:
%%timeit
a = np.random.randint(0,5,10)
mask1 = [a[1:]<=a[:-1]]
mask2 = [a[:-1]<=a[1:]]
mask1 = np.append(True, mask1)
mask2 = np.append(mask2, True)
mask = mask1 * mask2
a = a[mask]
a

25.6 µs ± 505 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Задача 18.
1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [118]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a[:,1] = np.sort(a[:,1])
a

[[0 5 8]
 [1 4 5]
 [5 0 1]]


array([[0, 0, 8],
       [1, 4, 5],
       [5, 5, 1]])

In [147]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a, a[:,1])
index = np.argsort(a[:,1], axis=0)
print(index)
a = a[[index], :]
a

[[5 6 1]
 [3 1 2]
 [8 4 4]] [6 1 4]
[1 2 0]


array([[[3, 1, 2],
        [8, 4, 4],
        [5, 6, 1]]])

Задача 19.
Поменяйте местами первую и вторую строки двумерного массива.

In [123]:
a = np.random.randint(0,9,9).reshape(3,3)
print(a)
a = a[[1,0,2], :]
a

[[0 0 0]
 [3 1 1]
 [4 7 1]]


array([[3, 1, 1],
       [0, 0, 0],
       [4, 7, 1]])

Задача 20
1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [224]:
a = np.arange(0,15,1).reshape(3,5)
print(a)
print(a[[0,2],:][:,[1,3]])
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  3]
 [11 13]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Задача 21
Что будет выведено на экран?


In [222]:
x = np.arange(5)
print(x[[0,0,1]])
# x[[0,0,1]] = range(3)
# print(x)
# x[[1,2,1]] += 1 # x[[1,2,1]] = x[[1,2,1]] + 1
print(x)

[0 0 1]
[0 1 2 3 4]


In [223]:
x[[1,2,1]] + 1

array([2, 3, 2])

Задача 22.
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [138]:
a = np.arange(0,1500,1).reshape(30,50)

In [183]:
%%timeit
a.flatten()

898 ns ± 30 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [185]:
%%timeit
a.ravel()

206 ns ± 2.77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [187]:
%%timeit
a.reshape(-1,)

566 ns ± 4.41 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [215]:
import timeit
a = np.arange(0,1500,1).reshape(30,50)
timeit.timeit(lambda: a.resize((a.shape[0]*a.shape[1],)),number=1)
# print(a)

8.047092705965042e-06

In [214]:
%%timeit
a.shape = (-1,)
# print(a)

196 ns ± 2.03 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
